# 接続先（内部URLに修正済み！）
spring.datasource.url=jdbc:postgresql://dpg-d72nlttm5p6s73cc0n60-a/galaxy_db_9716
spring.datasource.username=galaxy_user
spring.datasource.password=mMrIJPKZKYZBlaY8gOIVKSlqvQJfvRhV

# JPA設定
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# ポート設定
server.port=${PORT:8080}