# 接続先（新しいデータベースに修正！）
spring.datasource.url=jdbc:postgresql://dpg-d862u6egvqtc73eajf2g-a/danmaku_db_v2
spring.datasource.username=danmaku_db_v2_user
spring.datasource.password=VZ4bGbVxwATC8094LTY15NP4m4RHJP5N

# JPA設定
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# ポート設定
server.port=${PORT:8080}